<a href="https://colab.research.google.com/github/pdh0184/Festival_Data/blob/main/%EC%8B%9C%EC%99%B8%EB%B2%84%EC%8A%A4%ED%84%B0%EB%AF%B8%EB%84%90%EB%8D%B0%EC%9D%B4%ED%84%B0_%ED%96%89%EC%A0%95%EA%B5%AC%EC%97%AD_%EC%B6%94%EC%B6%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install googlemaps
import pandas as pd
import re

Requirement already satisfied: googlemaps in /usr/local/lib/python3.10/dist-packages (4.10.0)
Requirement already satisfied: requests<3.0,>=2.20.0 in /usr/local/lib/python3.10/dist-packages (from googlemaps) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2024.7.4)

In [ ]:
import chardet
#chardet 를 사용해서 인코딩을 자동 감지할 수 있다

# with open('/content/drive/MyDrive/Colab Notebooks/핵심 역량 프로젝트/고속버스_터미널별_이용인원_요일별.xlsx', 'rb') as file:
#     rawdata = file.read()
#     result = chardet.detect(rawdata)
#     encoding = result['encoding']

df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/핵심 역량 프로젝트/시외버스_터미널별_이용인원_요일별.xlsx')

df

,시/도,ID,이름,월,화,수,목,금,토,일
0,서울특별시,1053,김포공항,"2,231","2,114","2,092","2,222","2,377","2,303","2,326"
1,서울특별시,1089,동서울,"11,515","9,474","9,549","9,993","15,046","16,433","15,235"
2,서울특별시,1097,서울남부,"6,386","5,506","5,476","5,717","8,308","8,751","8,368"
3,서울특별시,1180,잠실역,345,284,272,287,371,444,403
4,서울특별시,1262,상봉,23,17,15,17,21,26,32
...,...,...,...,...,...,...,...,...,...,...
965,경상남도,2691,창원컨벤션센터,1,1,1,1,1,1,1
966,경상남도,4092,김해공항(국제선),22,23,29,28,32,29,25
967,경상남도,4093,김해공항(국내선),53,56,57,63,65,75,50
968,경상남도,4542,남해사거리,22,19,16,19,21,10,3
969,제주특별자치도,2320,제주시,72,70,74,74,98,101,98

In [ ]:
area_list = ['서울특별시', '부산광역시','인천광역시', '광주광역시', '울산광역시', '대전광역시', '대구광역시', '세종특별자치시', '제주특별자치도']
df_no_metropolitan_city = df[~df['시/도'].isin(area_list)]
df_no_metropolitan_city['자치 주소'] = df_no_metropolitan_city['시/도'] + ' ' + df_no_metropolitan_city['이름']

<ipython-input-11-c33fb23f8d7a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_metropolitan_city['자치 주소'] = df_no_metropolitan_city['시/도'] + ' ' + df_no_metropolitan_city['이름']

In [ ]:
df_metropolitan_city = df[df['시/도'].isin(area_list)]
df_metropolitan_city

         시/도    ID     이름       월      화      수      목       금       토       일
0      서울특별시  1053   김포공항   2,231  2,114  2,092  2,222   2,377   2,303   2,326
1      서울특별시  1089    동서울  11,515  9,474  9,549  9,993  15,046  16,433  15,235
2      서울특별시  1097   서울남부   6,386  5,506  5,476  5,717   8,308   8,751   8,368
3      서울특별시  1180    잠실역     345    284    272    287     371     444     403
4      서울특별시  1262     상봉      23     17     15     17      21      26      32
..       ...   ...    ...     ...    ...    ...    ...     ...     ...     ...
87     울산광역시  4114  옥동중학교       1      1      1      1       1       1       2
88   세종특별자치시  1054     세종     417    344    352    371     543     574     558
89   세종특별자치시  1077   세종청사     388    322    348    359     556     524     484
90   세종특별자치시  1900    조치원       8      6      6      7       8       8       7
969  제주특별자치도  2320    제주시      72     70     74     74      98     101      98

[92 rows x 10 columns]

In [ ]:
df_no_metropolitan_city

,시/도,ID,이름,월,화,수,목,금,토,일,자치 주소
91,경기도,1028,안양,176,127,124,128,215,292,269,경기도 안양
92,경기도,1029,수원,"2,258","1,655","1,682","1,733","2,955","3,908","3,868",경기도 수원
93,경기도,1032,송탄,185,161,158,159,211,266,213,경기도 송탄
94,경기도,1049,청평,76,66,63,61,72,64,74,경기도 청평
95,경기도,1051,평택대,279,272,264,267,288,284,199,경기도 평택대
...,...,...,...,...,...,...,...,...,...,...,...
964,경상남도,2297,석계,1,1,0,0,0,0,0,경상남도 석계
965,경상남도,2691,창원컨벤션센터,1,1,1,1,1,1,1,경상남도 창원컨벤션센터
966,경상남도,4092,김해공항(국제선),22,23,29,28,32,29,25,경상남도 김해공항(국제선)
967,경상남도,4093,김해공항(국내선),53,56,57,63,65,75,50,경상남도 김해공항(국내선)
968,경상남도,4542,남해사거리,22,19,16,19,21,10,3,경상남도 남해사거리

In [ ]:
df_no_metropolitan_city['자치 주소']

91             경기도 안양
92             경기도 수원
93             경기도 송탄
94             경기도 청평
95            경기도 평택대
            ...
964           경상남도 석계
965      경상남도 창원컨벤션센터
966    경상남도 김해공항(국제선)
967    경상남도 김해공항(국내선)
968        경상남도 남해사거리
Name: 자치 주소, Length: 878, dtype: object

# 광역시가 아닌 주소의 위경도 추출

In [ ]:
# 라이브러리 가져오기
import googlemaps
import pandas as pd

my_key = "AIzaSyDeWn3K49QFqYcsfc_ZPTDG7Va1hX2TumU"

# 구글맵스 객체 생성하기
maps = googlemaps.Client(key=my_key)  # my key값 입력

lat = []  #위도
lng = []  #경도

i=90
for place in df_no_metropolitan_city['자치 주소']:
    i = i + 1
    try:
        print(i, place)
        # 지오코딩 API 결과값 호출하여 geo_location 변수에 저장
        geo_location = maps.geocode(place)[0].get('geometry')
        lat.append(geo_location['location']['lat'])
        lng.append(geo_location['location']['lng'])
        print("지오코딩 API 전체 결과값 :", geo_location)
    except:
        lat.append('')
        lng.append('')
        print(i)

In [ ]:

#광역시가 아닌 지역의 위경도
df_no_metropolitan_city_latlng = pd.DataFrame({'위도':lat, '경도':lng})
print('\n')
print(df_no_metropolitan_city_latlng) #25~189번 인덱스

            위도          경도
0    37.402731  126.927918
1     37.28039  127.007785
2    37.084185  127.051427
3    37.729783  127.429345
4    36.994859  127.132955
..         ...         ...
873  35.369563  128.257013
874  35.202859  128.600092
875  35.172869  128.947178
876  35.272135  128.845228
877  34.838361  127.893984

[878 rows x 2 columns]

In [ ]:
import requests

def reverse_geocode(lat, lng, api_key):
    # Google Maps Geocoding API 엔드포인트
    endpoint = f"https://maps.googleapis.com/maps/api/geocode/json?latlng={lat},{lng}&key={api_key}&language=ko"

    # API 호출
    response = requests.get(endpoint)
    if response.status_code == 200:
        results = response.json()
        if results['status'] == 'OK':

            # 첫 번째 결과의 주소 반환
            #return dict(results)
            #return results['results'][0]['formatted_address']
            #return results['results'][0]['plus_code']['compound_code'][7:].replace(' ','')
            return results
        else:
            return "Geocoding API 요청 실패: " + results['status']
    else:
        return "Geocoding API 요청 실패"

# 테스트용 위도와 경도
latitude = 37.5665
longitude = 126.9780

# Google Cloud Console에서 발급받은 API 키
api_key = 'AIzaSyDeWn3K49QFqYcsfc_ZPTDG7Va1hX2TumU'

# 좌표를 주소로 변환
address = reverse_geocode(latitude, longitude, api_key)
print("위도:", latitude)
print("경도:", longitude)
print("주소:", address)

위도: 37.5665
경도: 126.978
주소: {'plus_code': {'compound_code': 'HX8H+H6R 대한민국 서울특별시', 'global_code': '8Q98HX8H+H6R'}, 'results': [{'address_components': [{'long_name': '110', 'short_name': '110', 'types': ['premise']}, {'long_name': '세종대로', 'short_name': '세종대로', 'types': ['political', 'sublocality', 'sublocality_level_4']}, {'long_name': '중구', 'short_name': '중구', 'types': ['political', 'sublocality', 'sublocality_level_1']}, {'long_name': '서울특별시', 'short_name': '서울특별시', 'types': ['administrative_area_level_1', 'political']}, {'long_name': '대한민국', 'short_name': 'KR', 'types': ['country', 'political']}, {'long_name': '04524', 'short_name': '04524', 'types': ['postal_code']}], 'formatted_address': '대한민국 서울특별시 중구 세종대로 110', 'geometry': {'location': {'lat': 37.5665851, 'lng': 126.9782038}, 'location_type': 'ROOFTOP', 'viewport': {'northeast': {'lat': 37.56793408029149, 'lng': 126.9795527802915}, 'southwest': {'lat': 37.5652361197085, 'lng': 126.9768548197085}}}, 'place_id': 'ChIJ81IZg_KifDURyA2TiacuQ3w', 'plus_code': {'compound_code': 'HX8H+J7 대한민국 서울특별시', 'global_code': '8Q98HX8H+J7'}, 'types': ['street_address']}, {'address_components': [{'long_name': 'HX8H+H6', 'short_name': 'HX8H+H6', 'types': ['plus_code']}, {'long_name': '서울특별시', 'short_name': '서울특별시', 'types': ['administrative_area_level_1', 'political']}, {'long_name': '대한민국', 'short_name': 'KR', 'types': ['country', 'political']}], 'formatted_address': 'HX8H+H6 대한민국 서울특별시', 'geometry': {'bounds': {'northeast': {'lat': 37.5665, 'lng': 126.978125}, 'southwest': {'lat': 37.566375, 'lng': 126.978}}, 'location': {'lat': 37.5665, 'lng': 126.978}, 'location_type': 'GEOMETRIC_CENTER', 'viewport': {'northeast': {'lat': 37.5677864802915, 'lng': 126.9794114802915}, 'southwest': {'lat': 37.5650885197085, 'lng': 126.9767135197085}}}, 'place_id': 'GhIJjZduEoPIQkARO99PjZe-X0A', 'plus_code': {'compound_code': 'HX8H+H6 대한민국 서울특별시', 'global_code': '8Q98HX8H+H6'}, 'types': ['plus_code']}, {'address_components': [{'long_name': '태평로1가', 'short_name': '태평로1가', 'types': ['political', 'sublocality', 'sublocality_level_2']}, {'long_name': '중구', 'short_name': '중구', 'types': ['political', 'sublocality', 'sublocality_level_1']}, {'long_name': '서울특별시', 'short_name': '서울특별시', 'types': ['administrative_area_level_1', 'political']}, {'long_name': '대한민국', 'short_name': 'KR', 'types': ['country', 'political']}], 'formatted_address': '대한민국 서울특별시 중구 태평로1가', 'geometry': {'bounds': {'northeast': {'lat': 37.5694861, 'lng': 126.9792094}, 'southwest': {'lat': 37.5656401, 'lng': 126.9755237}}, 'location': {'lat': 37.56770180000001, 'lng': 126.9772803}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 37.5694861, 'lng': 126.9792094}, 'southwest': {'lat': 37.5656401, 'lng': 126.9755237}}}, 'place_id': 'ChIJxwtWbO2ifDURj4QrUWrqv2U', 'types': ['political', 'sublocality', 'sublocality_level_2']}, {'address_components': [{'long_name': '세종대로', 'short_name': '세종대로', 'types': ['political', 'sublocality', 'sublocality_level_4']}, {'long_name': '중구', 'short_name': '중구', 'types': ['political', 'sublocality', 'sublocality_level_1']}, {'long_name': '서울특별시', 'short_name': '서울특별시', 'types': ['administrative_area_level_1', 'political']}, {'long_name': '대한민국', 'short_name': 'KR', 'types': ['country', 'political']}], 'formatted_address': '대한민국 서울특별시 중구 세종대로', 'geometry': {'bounds': {'northeast': {'lat': 37.5689814, 'lng': 126.9782607}, 'southwest': {'lat': 37.5568566, 'lng': 126.9723452}}, 'location': {'lat': 37.563054, 'lng': 126.9755254}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 37.5689814, 'lng': 126.9782607}, 'southwest': {'lat': 37.5568566, 'lng': 126.9723452}}}, 'place_id': 'ChIJXwA5qoyifDUREyhKPjwY4Ek', 'types': ['political', 'sublocality', 'sublocality_level_4']}, {'address_components': [{'long_name': '명동', 'short_name': '명동', 'types': ['political', 'sublocality', 'sublocality_level_2']}, {'long_name': '중구', 'short_name': '중구', 'types': ['political', 'sublocality', 'sublocality_level_1']}, {'long_name': '서울특별시', 'short_name': '서울특별시', 'types': ['administrative_area_level_1', 'political']}, {'long_name': '대한민국', 'short_name': 'KR', 'types': ['country', 'political']}], 'formatted_address': '대한민국 서울특별시 중구 명동', 'geometry': {'bounds': {'northeast': {'lat': 37.5693753, 'lng': 126.9908454}, 'southwest': {'lat': 37.5537278, 'lng': 126.9733139}}, 'location': {'lat': 37.55998, 'lng': 126.9858296}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 37.5693753, 'lng': 126.9908454}, 'southwest': {'lat': 37.5537278, 'lng': 126.9733139}}}, 'place_id': 'ChIJqxQ_G_GifDURDI7jheBrQzs', 'types': ['political', 'sublocality', 'sublocality_level_2']}, {'address_components': [{'long_name': '중구', 'short_name': '중구', 'types': ['political', 'sublocality', 'sublocality_level_1']}, {'long_name': '서울특별시', 'short_name': '서울특별시', 'types': ['administrative_area_level_1', 'political']}, {'long_name': '대한민국', 'short_name': 'KR', 'types': ['country', 'political']}], 'formatted_address': '대한민국 서울특별시 중구', 'geometry': {'bounds': {'northeast': {'lat': 37.5720231, 'lng': 127.0267966}, 'southwest': {'lat': 37.5438566, 'lng': 126.9615591}}, 'location': {'lat': 37.5601443, 'lng': 126.9959649}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 37.5720231, 'lng': 127.0267966}, 'southwest': {'lat': 37.5438566, 'lng': 126.9615591}}}, 'place_id': 'ChIJm_WhU_yifDURF56eaO5Ufl8', 'types': ['political', 'sublocality', 'sublocality_level_1']}, {'address_components': [{'long_name': '서울특별시', 'short_name': '서울특별시', 'types': ['locality', 'political']}, {'long_name': '서울특별시', 'short_name': '서울특별시', 'types': ['administrative_area_level_1', 'political']}, {'long_name': '대한민국', 'short_name': 'KR', 'types': ['country', 'political']}], 'formatted_address': '대한민국 서울특별시', 'geometry': {'bounds': {'northeast': {'lat': 37.7014549, 'lng': 127.1837949}, 'southwest': {'lat': 37.4282973, 'lng': 126.7644837}}, 'location': {'lat': 37.5518911, 'lng': 126.9917937}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 37.7014549, 'lng': 127.1837949}, 'southwest': {'lat': 37.4282973, 'lng': 126.7644837}}}, 'place_id': 'ChIJzWXFYYuifDUR64Pq5LTtioU', 'types': ['locality', 'political']}, {'address_components': [{'long_name': '서울특별시', 'short_name': '서울특별시', 'types': ['administrative_area_level_1', 'political']}, {'long_name': '대한민국', 'short_name': 'KR', 'types': ['country', 'political']}], 'formatted_address': '대한민국 서울특별시', 'geometry': {'bounds': {'northeast': {'lat': 37.7014549, 'lng': 127.1837949}, 'southwest': {'lat': 37.4282973, 'lng': 126.7644837}}, 'location': {'lat': 37.5518911, 'lng': 126.9917937}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 37.7014549, 'lng': 127.1837949}, 'southwest': {'lat': 37.4282973, 'lng': 126.7644837}}}, 'place_id': 'ChIJzzlcLQGifDURm_JbQKHsEX4', 'types': ['administrative_area_level_1', 'political']}, {'address_components': [{'long_name': '대한민국', 'short_name': 'KR', 'types': ['country', 'political']}], 'formatted_address': '대한민국', 'geometry': {'bounds': {'northeast': {'lat': 38.63400000000001, 'lng': 131.1603}, 'southwest': {'lat': 33.0041, 'lng': 124.5863}}, 'location': {'lat': 35.907757, 'lng': 127.766922}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 38.63400000000001, 'lng': 131.1603}, 'southwest': {'lat': 33.0041, 'lng': 124.5863}}}, 'place_id': 'ChIJm7oRy-tVZDURS9uIugCbJJE', 'types': ['country', 'political']}], 'status': 'OK'}

### 문제 있는 위경도 식별
- 이상한 위경도가 추출되는 문제점 발생
- 위경도 자리수가 10자리가 넘는 데이터는 문제가 있는 데이터이다

In [ ]:
import math

latlng = []
curious_area = []
#0부터 시작하는 인덱스가 필요
idx_temp = []

for idx, geo_df_row in df_no_metropolitan_city_latlng.iterrows() :

  try:
    str_num_lat = len(str(geo_df_row[0]).replace('.',''))
    str_num_lng = len(str(geo_df_row[1]).replace('.',''))

    if str_num_lat > 11:
      curious_area.append(idx +91)

    elif str_num_lng > 11:
      curious_area.append(idx + 91)

    else:
      latlng.append(idx+91)
      idx_temp.append(idx)
      print('위도 자리수 :' , str_num_lat, '경도 자리수 :' , str_num_lng )
      print(idx +91,':',geo_df_row[0] ,geo_df_row[1])

  except:
    curious_idx.append(idx+91)

curious_area

In [ ]:
print((latlng))
print(len(idx_temp))

[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 117, 118, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 160, 161, 162, 163, 164, 165, 166, 167, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 226, 227, 228, 229, 230, 231, 232, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 281, 282, 283, 284, 285, 286, 288, 289, 290, 291, 292, 293, 295, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 356, 357, 358, 359, 360, 362, 363, 364, 365, 366, 367, 368, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 392, 393, 394, 395, 396, 397, 398, 399, 400, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 421, 422, 423, 424, 425, 426, 427, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 460, 461, 462, 463, 465, 466, 467, 468, 469, 470, 471, 472, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 557, 558, 560, 561, 562, 563, 564, 565, 567, 569, 572, 573, 574, 575, 576, 577, 578, 580, 581, 582, 583, 584, 585, 586, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 708, 709, 710, 711, 712, 714, 715, 716, 719, 720, 721, 725, 726, 729, 730, 731, 733, 734, 739, 741, 745, 747, 749, 750, 753, 755, 756, 757, 759, 760, 763, 764, 765, 766, 767, 768, 769, 774, 775, 776, 782, 783, 784, 787, 788, 790, 791, 792, 793, 794, 795, 796, 799, 800, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 814, 815, 816, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 896, 897, 898, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 913, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 941, 943, 944, 947, 949, 950, 951, 954, 955, 957, 958, 959, 960, 961, 962, 963, 965, 966, 967, 968]
780

In [ ]:
# 이상한 데이터
df_no_metropolitan_city.loc[curious_area]

In [ ]:
#정상적인 데이터
df.iloc[latlng]
df_no_metropolitan_city.loc[latlng]

#정상적인 데이터의 위경도
#df_no_metropolitan_city_latlng.loc[idx_temp]

,시/도,ID,이름,월,화,수,목,금,토,일,자치 주소
91,경기도,1028,안양,176,127,124,128,215,292,269,경기도 안양
92,경기도,1029,수원,"2,258","1,655","1,682","1,733","2,955","3,908","3,868",경기도 수원
93,경기도,1032,송탄,185,161,158,159,211,266,213,경기도 송탄
94,경기도,1049,청평,76,66,63,61,72,64,74,경기도 청평
95,경기도,1051,평택대,279,272,264,267,288,284,199,경기도 평택대
...,...,...,...,...,...,...,...,...,...,...,...
963,경상남도,2285,가야,54,47,49,47,53,54,49,경상남도 가야
965,경상남도,2691,창원컨벤션센터,1,1,1,1,1,1,1,경상남도 창원컨벤션센터
966,경상남도,4092,김해공항(국제선),22,23,29,28,32,29,25,경상남도 김해공항(국제선)
967,경상남도,4093,김해공항(국내선),53,56,57,63,65,75,50,경상남도 김해공항(국내선)
968,경상남도,4542,남해사거리,22,19,16,19,21,10,3,경상남도 남해사거리

In [ ]:
#정상적인 위경도 값을 가진 행 주소를 딕셔너리로 저장
address_dict = {}
for idx, latlng in df_no_metropolitan_city_latlng.loc[idx_temp].iterrows():
    print(latlng[0], latlng[1])
    address = reverse_geocode(latlng[0], latlng[1], api_key)
    address_dict.update({idx+91 : address})

In [ ]:
address_dict.keys()

dict_keys([91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 117, 118, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 160, 161, 162, 163, 164, 165, 166, 167, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 226, 227, 228, 229, 230, 231, 232, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 281, 282, 283, 284, 285, 286, 288, 289, 290, 291, 292, 293, 295, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 356, 357, 358, 359, 360, 362, 363, 364, 365, 366, 367, 368, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 392, 393, 394, 395, 396, 397, 398, 399, 400, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 421, 422, 423, 424, 425, 426, 427, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 460, 461, 462, 463, 465, 466, 467, 468, 469, 470, 471, 472, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 557, 558, 560, 561, 562, 563, 564, 565, 567, 569, 572, 573, 574, 575, 576, 577, 578, 580, 581, 582, 583, 584, 585, 586, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 708, 709, 710, 711, 712, 714, 715, 716, 719, 720, 721, 725, 726, 729, 730, 731, 733, 734, 739, 741, 745, 747, 749, 750, 753, 755, 756, 757, 759, 760, 763, 764, 765, 766, 767, 768, 769, 774, 775, 776, 782, 783, 784, 787, 788, 790, 791, 792, 793, 794, 795, 796, 799, 800, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 814, 815, 816, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 896, 897, 898, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 913, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 941, 943, 944, 947, 949, 950, 951, 954, 955, 957, 958, 959, 960, 961, 962, 963, 965, 966, 967, 968])

In [ ]:
API_Failed = []
df_dict = {}
for i in address_dict.keys():
  try:
    data = address_dict[i]['results']
    desired_address = [item['formatted_address'] for item in data if item.get('formatted_address')]
    df_dict.update({i : desired_address[-3]})
    print(i,desired_address[-3])
  except:
    API_Failed.append(i)

In [ ]:
df = pd.DataFrame(df_dict.values(),index = df_dict.keys(), columns = ['진짜 주소'])
df

             진짜 주소
91    대한민국 경기도 안양시
92    대한민국 경기도 수원시
93    대한민국 경기도 평택시
94    대한민국 경기도 가평군
95    대한민국 경기도 평택시
..             ...
963  대한민국 경상남도 함안군
965  대한민국 경상남도 창원시
966     대한민국 부산광역시
967  대한민국 경상남도 김해시
968  대한민국 경상남도 남해군

[779 rows x 1 columns]

In [ ]:
df_no_metropolitan_city

,시/도,ID,이름,월,화,수,목,금,토,일,자치 주소
91,경기도,1028,안양,176,127,124,128,215,292,269,경기도 안양
92,경기도,1029,수원,"2,258","1,655","1,682","1,733","2,955","3,908","3,868",경기도 수원
93,경기도,1032,송탄,185,161,158,159,211,266,213,경기도 송탄
94,경기도,1049,청평,76,66,63,61,72,64,74,경기도 청평
95,경기도,1051,평택대,279,272,264,267,288,284,199,경기도 평택대
...,...,...,...,...,...,...,...,...,...,...,...
964,경상남도,2297,석계,1,1,0,0,0,0,0,경상남도 석계
965,경상남도,2691,창원컨벤션센터,1,1,1,1,1,1,1,경상남도 창원컨벤션센터
966,경상남도,4092,김해공항(국제선),22,23,29,28,32,29,25,경상남도 김해공항(국제선)
967,경상남도,4093,김해공항(국내선),53,56,57,63,65,75,50,경상남도 김해공항(국내선)
968,경상남도,4542,남해사거리,22,19,16,19,21,10,3,경상남도 남해사거리

In [ ]:
complete_df = pd.concat([df_no_metropolitan_city,df],axis =1 )

In [ ]:
df_metropolitan_city['진짜 주소'] =df_metropolitan_city['시/도']
df_metropolitan_city

<ipython-input-48-3ed17e25a23b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_metropolitan_city['진짜 주소'] =df_metropolitan_city['시/도']

,시/도,ID,이름,월,화,수,목,금,토,일,진짜 주소
0,서울특별시,1053,김포공항,"2,231","2,114","2,092","2,222","2,377","2,303","2,326",서울특별시
1,서울특별시,1089,동서울,"11,515","9,474","9,549","9,993","15,046","16,433","15,235",서울특별시
2,서울특별시,1097,서울남부,"6,386","5,506","5,476","5,717","8,308","8,751","8,368",서울특별시
3,서울특별시,1180,잠실역,345,284,272,287,371,444,403,서울특별시
4,서울특별시,1262,상봉,23,17,15,17,21,26,32,서울특별시
...,...,...,...,...,...,...,...,...,...,...,...
87,울산광역시,4114,옥동중학교,1,1,1,1,1,1,2,울산광역시
88,세종특별자치시,1054,세종,417,344,352,371,543,574,558,세종특별자치시
89,세종특별자치시,1077,세종청사,388,322,348,359,556,524,484,세종특별자치시
90,세종특별자치시,1900,조치원,8,6,6,7,8,8,7,세종특별자치시
969,제주특별자치도,2320,제주시,72,70,74,74,98,101,98,제주특별자치도

In [ ]:
complete_df = pd.concat([df_metropolitan_city , complete_df],axis = 0)
complete_df

,시/도,ID,이름,월,화,수,목,금,토,일,진짜 주소,자치 주소
0,서울특별시,1053,김포공항,"2,231","2,114","2,092","2,222","2,377","2,303","2,326",서울특별시,NaN
1,서울특별시,1089,동서울,"11,515","9,474","9,549","9,993","15,046","16,433","15,235",서울특별시,NaN
2,서울특별시,1097,서울남부,"6,386","5,506","5,476","5,717","8,308","8,751","8,368",서울특별시,NaN
3,서울특별시,1180,잠실역,345,284,272,287,371,444,403,서울특별시,NaN
4,서울특별시,1262,상봉,23,17,15,17,21,26,32,서울특별시,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
964,경상남도,2297,석계,1,1,0,0,0,0,0,NaN,경상남도 석계
965,경상남도,2691,창원컨벤션센터,1,1,1,1,1,1,1,대한민국 경상남도 창원시,경상남도 창원컨벤션센터
966,경상남도,4092,김해공항(국제선),22,23,29,28,32,29,25,대한민국 부산광역시,경상남도 김해공항(국제선)
967,경상남도,4093,김해공항(국내선),53,56,57,63,65,75,50,대한민국 경상남도 김해시,경상남도 김해공항(국내선)
968,경상남도,4542,남해사거리,22,19,16,19,21,10,3,대한민국 경상남도 남해군,경상남도 남해사거리

In [ ]:
complete_df.to_csv('/content/drive/MyDrive/Colab Notebooks/핵심 역량 프로젝트/시외버스터미널주소.csv', index=False)